---

- name: Add minikube user
  user:
    name: "{{ minikube_user }}"
    shell: /bin/bash

- name: add minikube user to docker group
  user:
    name: "{{ minikube_user }}"
    groups: "{{ docker_group }}"
    append: yes

- name: get required binaries and put to executables path
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  with_items: "{{ minikube_packages }}"

- name: download helm package
  get_url:
    url: "{{ minikube_helm_url }}"
    dest: "/tmp/helm.tar.gz"
    mode: 0644

- name: extract helm archive
  unarchive:
    src: "/tmp/helm.tar.gz"
    dest: "/tmp/"
    copy: false

- name: copy helm binary to executable path
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: yes
    mode: 0755

- name: start minikube
  shell:
    minikube start \
      --vm-driver=docker --memory=4000 \
      --kubernetes-version={{ minikube_kubernetes_version }}
  become_user: "{{ minikube_user }}"

- name: copy manifest script
  template:
    src: "k8s_manifest_script.sh.j2"
    dest: "/tmp/k8s_manifest_script.sh"
    mode: 0755

- name: execute manifest script to install k8s apps
  shell: bash /tmp/k8s_manifest_script.sh
  become_user: "{{ minikube_user }}"
